import fs from "node:fs/promises";
import openapiTS, { astToString } from "openapi-typescript";
import ts from "typescript";

const ast = await openapiTS(new URL("../docs/openapi.json", import.meta.url));
const names = ast.filter(node => node.name).map(node => node.name.text);
const directory = new URL("../packages/api-client/generated/", import.meta.url);
await fs.mkdir(directory, { recursive: true });
const outputs = [];
for (const node of ast) {
  if (ts.isInterfaceDeclaration(node) && astToString([node]).split("\n").length > 850) {
    const parts = [];
    let members = [];
    let lines = 0;
    const flush = () => {
      const name = `${node.name.text}Part${parts.length + 1}`;
      parts.push(name);
      outputs.push(ts.factory.updateInterfaceDeclaration(node, node.modifiers, name, node.typeParameters, node.heritageClauses, members));
      members = [];
      lines = 0;
    };
    for (const member of node.members) {
      const count = astToString([member]).split("\n").length;
      if (lines + count > 800 && members.length) flush();
      members.push(member);
      lines += count;
    }
    if (members.length) flush();
    await fs.writeFile(new URL(`${node.name.text}.ts`, directory),
      parts.map(name => `import type { ${name} } from "./${name}";`).join("\n") +
      `\nexport type ${node.name.text} = ${parts.join(" & ")};\n`);
  } else outputs.push(node);
}
for (const node of outputs) {
  if (!node.name) continue;
  const name = node.name.text;
  const body = astToString([node]);
  const used = new Set();
  function visit(child) {
    if (ts.isIdentifier(child) && names.includes(child.text) && child.text !== name) used.add(child.text);
    ts.forEachChild(child, visit);
  }
  visit(node);
  const imports = [...used].map(value => `import type { ${value} } from "./${value}";`).join("\n");
  const source = `// Generated by scripts/generate-api.mjs.\n${imports}\n${body}`;
  if (source.split("\n").length > 1000) throw new Error(`${name} exceeds 1000 lines; split the contract further.`);
  await fs.writeFile(new URL(`${name}.ts`, directory), source);
}
await fs.writeFile(new URL("../packages/api-client/schema.d.ts", import.meta.url), names.map(name => `export type { ${name} } from "./generated/${name}";`).join("\n") + "\n");
